export const cityFallbacks: Record<string, string[]> = {
  Owerri: [
    "Douglas Road",
    "Ikenegbu",
    "Aladinma",
    "World Bank Housing",
    "Nekede",
    "Egbu",
    "Ihiagwa",
    "New Owerri",
    "Trans-Egbu",
    "Orji",
  ],
  PortHarcourt: [
    "Mile 1",
    "Mile 3",
    "Mile 4",
    "GRA Phase 2",
    "Rumuola",
    "Rumuokoro",
    "Choba",
    "D-Line",
    "Diobu",
    "Ada George",
  ],
  Lagos: [
    "Yaba",
    "Ikeja",
    "Lekki",
    "Ajah",
    "Balogun Market",
    "Surulere",
    "Victoria Island",
    "Ikorodu",
    "Oshodi",
    "Mushin",
    "Ojuelegba",
  ],
  Abuja: [
    "Wuse",
    "Maitama",
    "Garki",
    "Utako",
    "Jabi",
    "Asokoro",
    "Gwarimpa",
    "Nyanya",
    "Kubwa",
  ],
  Enugu: [
    "New Haven",
    "Independence Layout",
    "Abakpa",
    "Uwani",
    "Ogui",
    "Trans-Ekulu",
    "Coal Camp",
    "Thinkers Corner",
  ],
  Benin: [
    "Uselu",
    "Ekosodin",
    "New Benin",
    "Sapele Road",
    "GRA",
    "Ring Road",
    "Oredo",
    "Ikpoba Hill",
    "Ugbowo",
  ],
  Uyo: [
    "Ewet Housing",
    "Itam",
    "Ikot Ekpene Road",
    "Nsikak Eduok",
    "Abak Road",
    "Shelter Afrique",
    "Oron Road",
  ],
  Aba: [
    "Ariaria Market",
    "Ngwa Road",
    "Osisioma",
    "Azikiwe Road",
    "Brass Junction",
    "Ogbor Hill",
  ],
  Onitsha: ["Main Market", "Ochanja", "Awka Road", "Nkpor", "Odoakpu", "Fegge"],
  Kano: [
    "Sabon Gari",
    "Kano Municipal",
    "Dala",
    "Gwale",
    "Fagge",
    "Hotoro",
    "Kofar Ruwa Market",
  ],
  Kaduna: [
    "Barnawa",
    "Kaduna North",
    "Ungwan Rimi",
    "Sabo",
    "Television",
    "Kawo",
    "Central Market",
  ],
  Jos: [
    "Terminus Market",
    "Rayfield",
    "Angwan Rukuba",
    "Bukuru",
    "Gyero",
    "Zarmaganda",
  ],
  Maiduguri: ["Baga Road Market", "Gomari", "Mairi", "Custom", "Bulunkutu"],
  Ilorin: ["Tanke", "Oja Oba", "Surulere", "Taiwo", "Geri Alimi"],
  Akure: ["Oba Adesida Road", "Oke Ijebu", "FUTA South Gate", "Araromi"],
  Ibadan: [
    "Bodija",
    "Dugbe",
    "Challenge",
    "Mokola",
    "Sango",
    "Apata",
    "Orita Mefa",
  ],
  Calabar: [
    "Marian Road",
    "Eight Miles",
    "Watt Market",
    "Ikot Ansa",
    "Goldie",
    "Akim",
  ],
  Warri: ["Effurun", "Ekpan", "Udu Road", "Airport Road", "Jakpa", "Okere"],
  Abeokuta: ["Panseke", "Kuto", "Oke Ilewo", "Ijaye", "Adigbe", "Lafenwa"],
  Makurdi: ["Wadata", "High Level", "Modern Market", "North Bank"],
};
