export const cityFallbacks: Record<string, string[]> = {
  Owerri: [
    "Douglas Road",
    "Ikenegbu",
    "Aladinma",
    "World Bank Housing",
    "Nekede",
    "Egbu",
    "Ihiagwa",
    "New Owerri",
    "Trans-Egbu",
    "Orji",
    "Aladinma Northern Extension",
    "Aladinma Estate",
    "Amawom",
    "Arugo Layout",
    "Ikenegbu Layout",
    "Imo State University",
    "State High Court",
    "Ugwu Orji",
    "Umueche",
    "Umuodu",
    "Umuoyima Emmanuel College Layout",
    "Uzi Layout",
    "Works Layout",
    "Amakohia",
    "Area A",
    "Area E",
    "Area H",
    "Avu",
    "Awo Omama",
    "Cherubim Junction",
    "Emekuku",
    "Ikenegbu Extension",
    "Imsu",
    "Irete",
    "Izombe",
    "Mgbidi",
    "New Owerri Capital Territory",
    "Wetheral",
    "Umuguma",
    "Orogwe",
    "Obinze",
    "Eziobodo",
    "Umuchima",
    "Owelu",
    "Wetheral Road",
    "Tetlow Road",
    "Mbaise Road",
    "Works Road",
    "Royce Road",
    "School Road",
    "Njemanze Street",
    "Old Market Road",
    "Old Okigwe Road",
    "Bank Road",
    "Christ Church Road",
    "Relief Market",
    "Ekeonuwa Market",
    "Rotobi Market",
    "Fire Service Roundabout",
    "Egbu Road",
    "Port Harcourt Road",
    "Aba Road",
    "Onitsha Road",
    "Okigwe Road",
    "Control Post Roundabout",
    "Assumpta",
    "Wetheral Roundabout",
    "IMSU Junction",
    " Okigwe Road",
    "MCC Road",
    "Amakohia Market",
    "Orlu Road axis",
    "Akwakuma Junction",
    "Nkwo Orji Market",
    "Warehouse Junction",
    // Residential Layouts & Estates
    "Akanawu Estate",
    "Chinelo Estate",
    "Okohia Estate",
    "Arugo Garden Estate",
    "Udenwa Estate",
    "Royal Garden Estate",
    "Graceland Garden Estate",
    "Orient Garden City",

    // Broader Neighborhoods & Suburbs
    "World Bank Housing Estate",
    "Umuguma ",
    "Imo Housing Estate",
    "Federal Low Cost Housing Estate",
    "World Bank Estate",
    "Nekede",
    "Obinze",
    "Irete",
    "Graceland location",

    // Premium Street / Landmark
    "Ojukwu Boulevard",
    // Suburban / Expansion Communities
    "Awaka",
    "Akwakuma",
    "Amakohia Uratta",
    "Okwu Uratta",
    "Orji Uratta",
    "Naze",
    "Emekuku",
    "Emii",
    "Agbala",
    "Ngor-Okpala",

    // University / Student Areas
    "FUTO Area ",
    "Umuchima",
    "Poly Nekede axis",
    "Imo State Polytechnic Umuagwo axis",

    // Other Notable Communities
    "Egbu-Uratta",
    "Obibiezena",
    "Obibieze",
    "Uratta",
    "Eziobodo",
    "Umuchima",
    "Umualum Nekede",
    "Avu",
    "Orogwe",
    "Owerre-Nchi-Ise",
    "Owerri ancient quarters",
    // Core Traditional Markets
    "Eke Ukwu Owerri Market",
    "Afo Owerre Market",
    "Nkwo Orji Market",
    "Relief Extension Market",
    "Timber Market (Naze)",
    "Building Materials Market (Naze)",

    // Junctions & Roundabouts
    "Spibat Junction",
    "Toronto Junction",
    "Control Post Roundabout (Assumpta Cathedral axis)",
    "Fire Service Roundabout",
    "Imo State University Junction",
    "Amakohia Flyover",
    "Akwakuma Junction",
    "Okigwe Road Roundabout",
    "Warehouse Junction",

    // Business & Lifestyle Streets
    "MCC Road",
    "Wetheral Roundabout axis",
    "Christ Church Road",
    "Okigwe Road",
    "Port Harcourt Road",
    "Aba Road",
    "Orlu Road",
    "Douglas by Mbaise Road",
    "Mbaise Road",
    "Rotibi Street",
    "Tetlow Road Extension",

    // Other Busy Spots
    "Imo Concorde Hotel axis",
    "Imo Specialist Hospital area",
    "Imo Palm Plantation junction",
  ],
  PortHarcourt: [
    // Neighborhoods / Areas
    "Abonnema Wharf",
    "Abuloma",
    "Ada George (AGIP Area)",
    "Aggrey Road",
    "Alakahia",
    "Artillery",
    "Borokiri",
    "Choba",
    "Creek Road",
    "Diobu",
    "D-Line",
    "East–West Road",
    "Eagle Island",
    "Elelenwo",
    "Elekahia",
    "Eleme",
    "Eliozu",
    "Garrison Junction",
    "GRA Phase 1",
    "GRA Phase 2",
    "GRA Phase 3",
    "GRA Phase 4",
    "GRA Phase 5",
    "Mile 1",
    "Mile 2",
    "Mile 3",
    "Mile 4",
    "Mgbuoba",
    "Marine Base",
    "Nkpogu",
    "New GRA",
    "NTA Road",
    "Nkpolu-Oroworukwo",
    "Ogbunabali",
    "Oil Mill Market",
    "Okija Street",
    "Old GRA",
    "Town (Old Township)",
    "Orogbum",
    "Oroazi",
    "Obiri-Ikwerre",
    "Peter Odili Road",
    "Rumuola",
    "Rumuibekwe",
    "Rumuigbo",
    "Rumuokwuta",
    "Rumuokoro",
    "Rumuokurusi",
    "Rumuolumeni",
    "Rumuepirikom",
    "Rumueme",
    "Rumuosi",
    "Rukpokwu",
    "Shell Cooperative Estate",
    "Stadium Road",
    "Trans-Amadi",
    "UPTH area",
    "Waterlines",
    "Woji",

    // Markets
    "Borokiri Market",
    "Choba Market",
    "Creek Road Market",
    "Fruit Garden Market",
    "Ikoku Spare Parts Market",
    "Mile One Market",
    "Mile Two Market",
    "Mile Three Market",
    "Mile Twelve Market",
    "Oil Mill Market",
    "Okija Market",
    "Rumuokoro Market",
    "Rumuosi Market",
    "Slaughter Market",
    "Town Market",

    // Estates / Residential / Landmarks
    "Gas Estate",
    "Golf Estate Axis",
    "Green Village Estate",
    "Lakeview Estate",
    "Naf Harmony Estate",
    "NLNG Area",
    "Pearl Spring Estate",
    "Greater Taf City",
    "Port Harcourt Pleasure Park",
    "Spar Mall Port Harcourt",
    "Genesis Mall Port Harcourt",
    "Everyday Supermarket GRA",
    "Market Square GRA",
  ],

  Lagos: [
    // Major roads & expressways (business-heavy corridors)
    "Lagos–Ibadan Expressway",
    "Lagos–Badagry Expressway",
    "Apapa–Oshodi Expressway",
    "Ikorodu Road",
    "Funsho Williams Avenue (Western Avenue)",
    "Agege Motor Road",
    "Herbert Macaulay Way (Yaba)",
    "Lekki–Epe Expressway",
    "Marina (Lagos Island)",
    "Broad Street (Lagos Island)",
    "Ahmadu Bello Way (Victoria Island)",
    "Adetokunbo Ademola Street (VI)",
    "Adeola Odeku Street (VI)",
    "Ozumba Mbadiwe Avenue (VI–Oniru)",
    "Akin Adesola Street (VI)",
    "Awolowo Road (Ikoyi)",
    "Alfred Rewane Road / Kingsway Road (Ikoyi)",
    "Kofo Abayomi Street (VI)",
    "Idowu Taylor Street (VI)",
    "Sanusi Fafunwa Street (VI)",
    "Water Corporation Drive (Oniru)",
    "Awolowo Way (Ikeja)",
    "Mobolaji Bank Anthony Way",
    "Oba Akran Avenue (Ikeja)",
    "Kudirat Abiola Way (Oregun)",
    "Adeniyi Jones Avenue (Ikeja)",
    "Allen Avenue (Ikeja)",
    "Opebi Road (Ikeja)",
    "Toyin Street (Ikeja)",
    "Acme Road (Ogba/Oregun)",
    "Adekunle Fajuyi Way (Ikeja GRA)",
    "Lateef Jakande Road (Agidingbi)",
    "Agidingbi Road (Ikeja)",
    "Airport Road (Murtala Muhammed Int'l)",
    "Wharf Road (Apapa)",
    "Creek Road (Apapa)",
    "Dockyard Road (Apapa)",
    "Apapa–Tin Can Island Port Corridor",
    "Ago Palace Way (Okota)",
    "Okota Road",
    "Lawanson Road (Surulere)",
    "Adeniran Ogunsanya Street (Surulere)",
    "Bode Thomas Street (Surulere)",
    "Ojuelegba Road (Surulere)",
    "Commercial Avenue (Yaba)",
    "Tejuosho Road (Yaba)",
    "Igbosere Road (Lagos Island)",
    "Adeniji Adele Road (Lagos Island)",

    // Bridges & causeways (key business links)
    "Third Mainland Bridge",
    "Eko Bridge",
    "Carter Bridge",
    "Lekki–Ikoyi Link Bridge",

    // Major junctions & interchanges
    "Ojota Interchange",
    "Maryland Junction",
    "Anthony Bus Stop",
    "Fadeyi Bus Stop",
    "Onipanu Bus Stop",
    "Palmgrove Bus Stop",
    "Obanikoro Bus Stop",
    "Ketu Bus Stop",
    "Mile 12 Bus Stop",
    "Berger (Ojodu Berger) Bus Stop",
    "Oshodi Transport Interchange",
    "Iyana Ipaja",
    "Iyana Iba",
    "Cele Bus Stop",
    "Mile 2 Interchange",
    "Costain Roundabout",
    "Barracks Bus Stop (Surulere)",
    "CMS (Marina) Bus Stop",
    "Obalende Roundabout",
    "Tinubu Square / CMS axis",
    "Adekunle Interchange (Yaba–Third Mainland)",
    "Jibowu Interchange",
    "Yaba Bus Stop",
    "Lekki Phase 1 Gate Roundabout",
    "Lekki Toll Plaza (Admiralty)",
    "Chevron Drive Junction",
    "Jakande Roundabout (Lekki)",
    "Ajah Jubilee Bridge Roundabout",
    "Abule Egba Flyover Interchange",
    "Volkswagen (VW) Bus Stop",
    "Alakija Bus Stop",
    "Trade Fair Bus Stop",
    "Apongbon/CMS Interchange",
    "Iganmu Interchange",
    "Maza-Maza Bus Stop",

    // Central markets & trade hubs
    "Balogun Market",
    "Idumota Market",
    "Jankara Market",
    "Ebutte Ero Market",
    "Oyingbo Market",
    "Tejuosho Main Market (Yaba)",
    "Computer Village (Otigba, Ikeja)",
    "Alaba International Market (Ojo)",
    "Ladipo Auto Spare Parts Market (Mushin)",
    "Mile 12 Market (Ketu)",
    "Daleko Food Market (Mushin/Isolo)",
    "Aswani Market (Isolo)",
    "Arena Market (Oshodi/Bolade)",
    "Oshodi Market",
    "Ile Epo Market (Abule Egba)",
    "Katangowa (Super) Market (Abule Egba)",
    "Iyana Iba Market (Ojo)",
    "Lagos International Trade Fair Complex",
    "ASPAMDA Market (Trade Fair Complex)",
    "BBA Market (Balogun Business Association, Trade Fair Complex)",
    "Epe Fish Market",
    "Jakande Market (Lekki)",
    "Ajah Market (Under Bridge)",
    "Sangotedo Market",
    "Oniru Market",
    "Lekki Arts & Crafts Market (Oba Elegushi)",
    "Agege Market",
    "Ogba Retail Market",
    "Ikeja New Garage Market",
    "Ojuwoye Market (Mushin)",
    "Boundary Market (Ajegunle)",
    "Iddo Market",
    "Iponri Market",
    "Aguda Market (Surulere)",
    "Itire Market (Surulere)",
    "Banana Island",
    "Victoria Garden City (VGC)",
    "Parkview Estate",
    "Dolphin Estate",
    "Pinnock Beach Estate",
    "Chevy View Estate",
    "Orchid Court Estate",
    "Lekki Gardens Estate",
    "Friends Colony Estate",
    "Northern Foreshore Estate",
    "Atlantic View Estate",
    "Amen Estate",
    "Carlton Gate Estate",
    "Cowry Creek",
    "Victory Park Estate",
    "G Cappa Estate",
    "Okupe Estate",
    "Omole Phase 1 Estate",
    "Ikota Villa Estate",
    "Osapa London Estate",
    "Grenadine Homes Citiview Estate",
    "The Glenmore Estate (Awoyaya)",
    "Maiyegun Beach Estate",
    "Pearl View Estate",

    // Suburban / Expansion Communities
    "Epe",
    "Sangotedo",
    "Ajah",
    "Ibeju-Lekki",
    "Ikorodu",
    "Magodo",
    "Gbagada",
    "Abule Egba",
    "Badagry",
    "Festac Town",
    "Ojodu",
    "Alimosho",
    "Eko Atlantic City",
    "Abijo GRA",
    "Gracefield Island",
    "Isimi Lagos",
    // Micro-Markets & Specialty Trade Hubs
    "Jankara Market",
    "Oyingbo Market",
    "Aswani Market (Isolo)",
    "Epe Fish Market",
    "Daleko Food Market",
    "Arena Market (Oshodi)",
    "Oshodi Market (Isopakodowo)",

    // Landmark Lifestyle & Retail Venues
    "Silverbird Galleria",
    "Landmark Lagos (Oniru)",
    "Kings Tower (Ikoyi)",
    "Heritage Place (Ikoyi)",
    "Civic Tower (Victoria Island)",
    "The Wings Towers (Victoria Island)",
    "Broad Street (Lagos Island)",
    "Awolowo Road (Ikoyi)",
    "Adeniran Ogunsanya Street (Surulere)",
    "Isaac John Street (Ikeja GRA)",
    "Allen Avenue (Ikeja)",
    "Ajose Adeogun",
    "Adeola Odeku",
    "Ozumba Mbadiwe",
    "corridors",
    "Yaba",
    "Unilag – Akoka",
    "LASU – Ojo/Iba",
    "Covenant/Unilorin private student clusters",
    "CMS – Marina corridor",
    "E-Center Commercial Complex (Yaba)",
    "Surulere Leisure/Entertainment Corridor (Ojuelegba–National Stadium)",
  ],
  Abuja: [
    // Major Roads & Corridors
    "Umaru Musa Yar’Adua Expressway (Airport Expressway)",
    "Abuja–Kaduna Highway (southern section)",
    "Herbert Macaulay Way",
    "Ahmadu Bello Way",
    "Murtala Muhammed Expressway",
    "Ring Road 1",
    "Ring Road 2",
    "Ahmadu Bello Way (Gwarinpa access)",

    // Key Junctions & Interchanges
    "Utako Interchange",
    "Garki Interchange",
    "Wuse Zone 3 Roundabout",
    "Maitama Junction (CBD access)",

    // Central Markets & Trade Hubs
    "Wuse Market (Zone 5)",
    "Banex Plaza (Wuse 2 electronics hub)",
    "Garki International Market",
    "Utako Market",
    "Nyanya Market",
    "Dutse Market",
    "Kado Fish Market",
    "Building Materials Market – Dei-Dei",

    // Residential Layouts, Estates & Gated Communities (Abuja — business-heavy / mixed-use)
    "Central Business District (CBD)",
    "Asokoro",
    "Asokoro Extension",
    "Maitama",
    "Maitama II (Cadastral Zone A10)",
    "Minister’s Hill (Maitama)",
    "Wuse 2",
    "Wuse (Zones 1–7)",
    "Garki (Areas 1–11)",
    "Jabi",
    "Jabi Lake District",
    "Utako",
    "Wuye",
    "Mabushi",
    "Kado",
    "Jahi",
    "Katampe",
    "Katampe Extension",
    "Guzape",
    "Apo (Apo Resettlement/Apo Dutse)",
    "Gudu",
    "Durumi",
    "Kaura District (Games Village axis)",
    "Life Camp",
    "Dakwo/Dakibiyu",

    "Gwarinpa Estate",
    "Citec Villa (Gwarinpa/Life Camp axis)",
    "Brains & Hammers City (Life Camp)",
    "Godab Estate (Life Camp/Kafe District)",
    "Aco Estate (Life Camp)",
    "Efab City Estate (Mbora/Nbora)",
    "Efab Estate (Lokogoma axis)",
    "Sunnyvale Homes (Dakwo)",
    "Sun City Estate (Galadimawa axis)",
    "Crown Court Estate (Durumi)",
    "Prince & Princess Estate (Gaduwa axis)",
    "NAF Valley Estate (Asokoro)",
    "NNPC Quarters (Area 11, Garki)",
    "CBN Quarters (Garki/Utako corridors)",
    "Kado Estate",
    "Games Village (Kaura District)",

    // Suburban / Expansion Communities & Satellite Towns with Business Activity
    "Lokogoma",
    "Lugbe",
    "Kuje",
    "Kubwa",
    "Nyanya",
    "Karsana",
    "Galadimawa",
    "Old Nyanya",
    "Karu",
    "Jikwoyi",
    "Gwagwalada",
    "Orozo",

    // Major Markets & Commercial Micro-Hubs
    "Wuse Market",
    "Utako Market",
    "Garki International Market",
    "Dutse Market",
    "Nyanya Market",
    "Kubwa Village Market",
    "Gwagwalada Market",
    "Karu Market",

    // Landmark Junctions / Business Concentration Zones
    "Banex Plaza - Wuse II ",
    "Area 1 Shopping Complex",
    "Area 10 Shopping Complex",
    "Garki Ultra Modern Market",
    "UTC Area 10 (electronics & gadgets hub)",
    "Area 11 Shopping Complex",
    "Berger Junction (transport/business hub)",
    "Nyanya Motor Park",
    "Jabi Motor Park",

    // Lifestyle, Hospitality & Event Hubs
    "Jabi Lake Mall",
    "Ceddi Plaza (CBD)",
    "Silverbird Entertainment Centre (CBD)",
    "Shoprite Apo Mall",
    "Grand Square (Central Business District)",
    "Wuse II Nightlife Street (Adetokunbo Ademola Crescent)",
    "Maitama Amusement Park",
    "Millennium Park (tourist & leisure spot)",
    "Bolingo Hotels & Towers (CBD hospitality hub)",
  ],
  Enugu: [
    // Major Roads & Corridors
    "Enugu–Onitsha Expressway",
    "Enugu–Port Harcourt Expressway",
    "Abakaliki Road",
    "Ogui Road",
    "Zik Avenue",
    "Chime Avenue",
    "Okpara Avenue",
    "Presidential Road",
    "Agbani Road",
    "Nike Lake Road",
    "Akanu Ibiam Int’l Airport Road",
    "Emene Road",
    "Independence Avenue",
    "Rangers Avenue",
    "Bisala (Bissala) Road",
    "Iva Valley Road",
    "New Market Road",
    "Trans-Ekulu Corridor",
    "Old Abakaliki Road",
    "NTA/ESBS - Achi Street",

    // Junctions & Interchanges
    "Holy Ghost Roundabout",
    "Ogui Junction - Abakaliki Road",
    "Otigba Junction",
    "New Market Roundabout",
    "New Haven Junction",
    "ESBS Junction",
    "WAEC Roundabout",
    "Abakpa-Nike Junction",
    "Roban Roundabout",
    "Njemanze Roundabout",
    "China Town Ward",

    // Central Markets & Retail Hubs
    "Ogbete Main Market",
    "New Market",
    "Aria Market",
    "Old Artisan Market",
    "New Artisan Market",
    "Phase II Market",
    "Kenyatta Timber Market",
    "Gariki Market",
    "Abakpa Nike Market",
    "Auto/Spare Parts Market",
    "Orie Emene Community Market",
    "New Haven Market",
    "Mayor Market",
    "Polo Park Mall",

    // Additional Markets (extended list)
    "Akwata Market",
    "Thinkers Corner Market",
    "Keneta Market",
    "Ugwuaji Market",
    "Agbani Market",
    "Nkwo Nike Market",
    "Afor Awkunanaw Market",
    "Orie Orba Market",
    "Coal Camp Market",
    "Garki Market",

    // Government & Institutional Zones
    "ESUT - Agbani",
    "UNEC - Ogui Road",
    "IMT - Independence Avenue",
    "Enugu State Polytechnic",
    "Caritas University",
    "Godfrey Okoye University",
    "Coal City University",
    "ESCET - Abakaliki Road",

    // Hospitality, Lifestyle & Leisure Hubs
    "Nike Lake Resort",
    "Okpara Square",
    "Michael Okpara Statue Square",
    "Enugu Golf Course/Club (GRA)",
    "Roban Stores Complex",
    "Nza Street",

    // Major Residential Estates / Layouts
    "Independence Layout",
    "GRA",
    "Achara Layout",
    "Uwani",
    "Coal Camp",
    "Asata",
    "Thinkers Corner",
    "New Haven",
    "Maryland",
    "Abakpa Nike",
    "Trans Ekulu",
    "Awkunanaw",
    "Emene",
    "Ogui",
    "Amechi",
    "Nike Lake Area",

    // Estates & Modern Housing Areas
    "Centenary City Estate",
    "Golf Estate",
    "Fidelity Estate",
    "Ekulu West Estate",
    "Premier Layout",
    "Christ Embassy Estate",
    "WTC Estate",

    // Satellite Towns / Business-Linked Communities
    "Nsukka",
    "9th Mile",
    "Agbani",
    "Ugwuaji",
    "Opi",
    "Udi",
    "Awgu",
    "Ngwo",
  ],
  Benin: [
    "Uselu",
    "Ekosodin",
    "New Benin",
    "Sapele Road",
    "GRA",
    "Ring Road",
    "Oredo",
    "Ikpoba Hill",
    "Ugbowo",
    // Major Roads & Corridors
    "Sapele Road",
    "Airport Road",
    "Akpakpava Road",
    "Ekenwan Road",
    "Ugbowo–Lagos Road",
    "Upper Sakponba Road",
    "Mission Road",
    "Siluko Road",
    "New Lagos Road",
    "Uselu–Lagos Road",
    "Ikpoba Hill Road",
    "Ihama Road",
    "Boundary Road",
    "Wire Road",
    "Ring Road",
    "King’s Square",
    "Oba Market Road",
    "Dawson Road",
    "Ekewan Barracks Road",

    // Junctions & Interchanges
    "Ramat Park",
    "Uselu",
    "Ekehuan",
    "Akpakpava",
    "Upper Sakponba",
    "Adesuwa",
    "Oredo",
    "Ogunmwenyin",

    // Central Markets & Retail Hubs
    "Oba Market",
    "New Benin Market",
    "Uselu Market",
    "Ekiosa Market",
    "Ekiuwa Market",
    "Agbado Market",
    "Oliha Market",
    "Ekewan Market",
    "Ramat Market",
    "Edaiken Market",
    "Ikpoba Hill Market",
    "Oredo Market",
    "Ogida Market",

    // Major Residential Layouts & Areas
    "GRA Benin",
    "Ugbowo",
    "Uselu",
    "Ikpoba Hill",
    "Upper Sakponba",
    "Oredo",
    "Oliha",
    "Ugbor Village Road",
    "Ihama/Adesuwa ",
    "Siluko Road",
    "Sapele Road Housing",
    "Ekenwan Barracks",
    "Boundary Road Layout",
    "Ogida",
    "Agbado",
    "Edaiken",
    "Aduwawa",
    "Etete",
    "Okhoro",
    "Upper Mission Extension",

    // Hospitality, Lifestyle & Leisure Areas
    "GRA Benin Leisure",
    "Adesuwa/Ihama",
    "Airport Road",
    "Ugbor–Etete",
  ],
  Uyo: [
    "Oron Road",
    "Abak Road",
    "Ikot Ekpene Road",
    "Nwaniba Road",
    "Nsikak Eduok",
    "Udo Udoma",
    "Atiku Abubakar Avenue",
    "Edet Akpan Avenue",
    "Four Lane",
    "Ewet Housing Estate",
    "Barracks Road",
    "Wellington Bassey Way",
    "Nwaniba Extension",
    "Aka Road",
    "Ekpenyong Street",

    // Junctions & Roundabouts
    "Itam Junction",
    "Itam Market Junction",
    "Plaza Roundabout",
    "Ibom Plaza",
    "Nwaniba Junction",
    "Ikpa Road Junction",
    "Abak Road Junction",
    "Atiku Junction",
    "Eket Oron Road Roundabout",

    // Markets & Commercial Hubs
    "Itam Market",
    "Akpan Andem Market",
    "Urua Ikpa Market",
    "Urua Nka Market",
    "Mbiabong Market",
    "Urua Udoma Market",
    "Urua Ekpa Market",
    "Urua Essien Udim Market",
    "Urua Akpan Andem",
    "Urua Obong Market",

    // Residential & Business Districts
    "Ewet Housing Estate",
    "Shelter Afrique Estate",
    "Osongama Estate",
    "Nwaniba Layout",
    "Atan Offot",
    "Itam",
    "Afaha Offot",
    "Nsukara Offot",
    "Uyo Village Road",
    "Iboko Offot",
    "Use Offot Area",
    "Aka Etinan Road",
    "Nung Udoe",

    // Lifestyle, Leisure & Business Zones
    "Ibom Plaza",
    "Udo Udoma Avenue",
    "Nsikak Eduok Avenue",
    "Ewet Housing Estate",
    "Nwaniba Road Resort",
    "Ibom Hotel",
    "Ikot Ekpene Road",
  ],
  Aba: [
    "Ngwa Road",
    "Azikiwe Road",
    "Enyimba Road",
    "Owerri Road",
    "Port Harcourt Road",
    "Old Umuahia Road",
    "New Umuahia Road",
    "Osisioma Road",
    "Bende Road",
    "Diversion Road",
    "Railway Station Road",
    "Aba–Eket Road",
    "Aba–Umuahia Expressway",
    "Aba–Port Harcourt Highway",
    "Aba–Owerri Highway",
    "Brass Junction",
    "Eziukwu Roundabout",
    "New Market Junction",
    "Osaina Junction",
    "Ngwa Road Junction",
    "Port Harcourt Road Junction",
    "World Bank Junction",
    "Theater Junction",
    "Railway Junction",
    "Ilo Roundabout",
    "Umuola Junction",

    "Ariaria Industrial",
    "Works",
    "Eziukwu Industrial",
    "World Bank Industrial",
    "Old Ngwa Road Industrial",

    "World Bank",
    "Trinity",
    "Uratta",
    "Eziukwu",
    "Azikiwe",
    "Pearl",
    "Isiala Ngwa",
    "Enyimba",
    "Christ the King",
    "Progressive",
    "Amaise",

    "Osisioma",
    "Uratta",
    "Eziukwu",
    "Ogbor Hill",
    "Ekeoha",
    "Afugiri",
    "Aba South",
    "Aba North",

    "Amaise",
    "Agulu",
    "Umuenyim",
    "Ofeme",
    "Okporowo",
    "Okwu",
    "Umuoke",
    "Aba South",
    "Aba North",
    "Atani",
    "Olibie",
    "Eziukwu North",
    "Eziukwu South",
    "Okiri",
    "Ukwa",
    "Nezobido",
    "Umueberi",
    "Onitsha Junction",
    "Afobolu",
    "Igbere",
    "Umuogele",
    "Umudike Junction",
    "Ekeoma",
    "Eziama",
    "Oko Central",
    "Umuorie",
    "Umuokpu",
    "Umuagu",
    "Iheke",
    "Ofuma",
    "Umunkama",
    "Umuokele",
    "Umuaria",
    "Okwokwe",
    "Umuasonye",
    "Ogene",
    "Umuodike",
    "Amuzukwu North",
    "Amuzukwu South",
    "Oloja",
    "Umuchukwu",
    "Umuezeala",
    "Umueleke",
    "Mgboko",
    "Nkwoatani",
    "Umutei",
    "Umueso",
    "Alaoji",
    "Okporo",
    "Umuegwu Ngwa",
    "Okwereke",
  ],
  Umuahia: [
    // Major Roads & Corridors
    "Aba Road",
    "Ikot Ekpene Road",
    "Uzuakoli Road",
    "Bende Road",
    "Mission Hill Road",
    "Azikiwe Road",
    "Umudike Road",
    "Umuahia-Okigwe Road",
    "Umuahia-Uzuakoli Road",
    "Afara Road",
    "Warri Street",
    "Awolowo Street",
    "Eket Street",
    "Mbawsi Road",
    "Factory Road",

    // Junctions & Roundabouts
    "Isi Gate Junction",
    "Ubakala Junction",
    "Old Umuahia Junction",
    "Okpara Square",
    "Amuzukwu Junction",
    "Government House Roundabout",
    "Ossah Junction",
    "Aba Road Flyover",
    "Orie Ugba Junction",

    // Markets & Commercial Hubs
    "Umuahia Main Market",
    "Isi Gate Market",
    "Ubani Ibeku Market",
    "Orie Ugba Market",
    "Ndoro Market",
    "Ahiaeke Market",
    "Ahiaukwu Market",
    "Industrial Market Umuahia",
    "Nkwo Egwu Market",
    "Ossah Market",
    "Orie Umuahia Market",

    // Residential & Estates
    "Afara Housing Estate",
    "Low-Cost Housing Estate",
    "Umuopara Housing Area",
    "Amuzukwu Layout",
    "Ossah Layout",
    "Isi Court Layout",
    "Agbama Housing Estate",
    "Federal Low Cost Housing",
    "Aba Road Layout",
    "Umuahia Town Centre",

    // Business & Lifestyle Zones
    "Isi Gate",
    "Okpara Square",
    "Umuahia Main Market",
    "Factory Road",
    "Mission Hill",
    "Ossah Gateway",

    // Satellite Towns & Communities
    "Ubakala",
    "Old Umuahia",
    "Afara Ukwu",
    "Amuzukwu Ibeku",
    "Ossah",
    "Umuopara",
    "Ndume",
    "Ohuhu",
    "Umuokpara",
    "Mbawsi",
    "Amachara",
    "Nkata Ibeku",
    "Nkwoegwu",
    "Umuahia South",
    "Umuahia North",
    "Ezeleke",
    "Ahiaeke",
    "Amakama",
    "Umuariaga",
    "Ohiya",

    // Peri-Urban Business Clusters
    "Ubani Ibeku Industrial",
    "Ndoro Timber Market",
    "Umuopara Industrial ",
    "Ohiya Industrial Cluster",
    "Amachara Development",

    // Transport / Gateway Corridors
    "Ubakala Junction",
    "Afara Junction",
    "Ohiya Railway",
    "Umuopara Gateway Road",
    "Ossah Airport Road",

    // Core Urban Extensions
    "Isi Court",
    "Amuzukwu Layout",
    "Amachara Layout",
    "Eket Street Axis",
    "Azikiwe Road Layout",
    "Agbama Estate",
    "Low-Cost Housing Estate",
    "World Bank Housing Estate",
    "Mission Hill",
    "Government Layout",
    "Orie Ugba Area",
    "Okwulaga Afara",
    "Okwoyi Ibeku",

    // Suburban & Semi-Urban Hubs
    "Umuopara Housing Estate",
    "Ohiya Mechanic Village",
    "Ubakala Housing Area",
    "Ndume Timber Cluster",
    "Ahiaeke Ndume",
    "Isingwu",
    "Nkwoegwu Market",
    "Nkwoachara",
    "Ahieke Ndume",
    "Ariam Usaka Belt",

    // Transport & Junction Corridors
    "Ubakala Expressway Corridor",
    "Ossah Expressway",
    "Ohiya Junction Axis",
    "Ubakala Junction",
    "Ahieke Junction",
    "Ubani Junction",
    "Umuariaga Michael Okpara",
    "Isigate Junction",

    // Periphery & Growth Settlements
    "Ekeoba",
    "Okaiuga Nkwoegwu",
    "Ndume Ibeku",
    "Okwoyi Afara",
    "Amaokwe Item Belt",
    "Umuekwule Afugiri",
    "Umuagu Ibeku",
    "Ariam Market Cluster",
  ],
  Onitsha: [
    "Upper Iweka Road",
    "Awka Road",
    "Ogbaru Road",
    "Obosi Road",
    "Nkpor-Ogidi Expressway",
    "Ogidi Road",
    "Obosi Road",
    "Ochanja Road",
    "River Port Road",
    "New Market Road",
    "Creek Road",
    "Zik’s Avenue",

    "American Quarters",
    "GRA",
    "Beverly Hills Estate",
    "Federal Housing Estate 3-3",
    "Federal Housing Estate Fegge",
    "Oba",
    "Nkpor",
    "Fegge",
    "Bridgehead",

    "Nkpor Junction",
    "Onitsha Railway Station Area",

    "Main Market",
    "Ochanja Market",
    "Ogboefere Market",
    "Relief Market",
    "Electric Market",
    "Building Material Market",
    "Stock Fish Market",
    "Ogbo-Abada Market",
    "Plastic Market",
    "Aluminium & Glass Market",
    "Iron/Steel Market",
    "New Spare Parts Market",
    "Tyre Market",
    "Motor Spare Parts Market",
    "Drug Market",
    "Tech Hub (Emeka Offor Plaza)",

    "Nkpor",
    "Obosi",
    "Ogidi",
    "Umuoji",
    "Ogbunike",
    "Nkwelle-Ezunaka",
    "Awka-Etiti",

    "Niger Bridge",
    "Onitsha River Port",
    "Ogbunike Caves",

    "Odoakpu",
    "Fegge",
    "Woliwo",
    "Ose-Okwodu",
    "Ogbakuba",
    "Odoakpu Village",
    "Okpoko",
    "Ochanja",
    "Bridgehead",
    "New Market",
    "Otu",
  ],
  Kano: [
    "Sabon Gari",
    "Kano Municipal",
    "Dala",
    "Gwale",
    "Fagge",
    "Hotoro",
    "Kofar Ruwa Market",
    // Major Roads & Corridors
    "Zaria Road",
    "Maiduguri Road",
    "Gwarzo Road",
    "BUK Road",
    "Audu Bako Way",
    "Aminu Kano Way",
    "Tarauni Road",
    "Kofar Ruwa Road",
    "IBB Way",
    "Aminu Kano Expressway",
    "Sabon Gari Road",

    // Key Junctions & Interchanges
    "Dan Agundi Junction",
    "Tal’udu Junction",
    "Gidan Malam Aminu Kano Junction",
    "Ibrahim Taiwo",
    "Civic Centre Intersection",
    "Tarauni Market Junction",

    // Central Markets
    "Sabon Gari Market",
    "Kantin Kwari Market",
    "Dawanau International Grain Market",
    "Singer Market",
    "Kofar Wambai Market",
    "Yankaba Market",
    "Kurmi Market",
    "Farm Centre Market",
    "Sharada Market",
    "Kofar Ruwa Market",
    "Sabuwar Gandu Market",
    "Abubakar Rimi Market",

    // Trade / Specialty Clusters
    "Sabon Gari Electronics Line",
    "Kantin Kwari Textile Hub",
    "Singer Electronics & Spare Parts Cluster",
    "Dawanau Grain & Produce Hub",
    "Yankaba Foodstuff Market",

    // Major Industrial Estates
    "Sharada Industrial Estate",
    "Bompai Industrial Estate",
    "Challawa Industrial Estate",
    "Kumbotso Industrial Zone",
    "Hadejia Road Industrial Layout",
    "Dakata Industrial Layout",

    // Business & Commercial Layouts
    "Farm Centre",
    "Zaria Road",
    "Hotoro Business Layout",
    "Naibawa Industrial Cluster",
    "Rijiyar Zaki Industrial Area",

    // Hotels & Hospitality Landmarks
    "Bristol Palace Hotel",
    "Tahir Guest Palace",
    "Royal Tropicana Hotel",
    "Prince Hotel",
    "R & K Guest Palace",
    "Grand Central Hotel",
    "Niima Guest Inn",
    "Mozida Suites",
    "Porto Golf Resort - Tiga",

    // Malls & Shopping Complexes
    "Ado Bayero Mall",
    "Kano City Mall",
    "Sabon Gari Plaza",
    "Farm Centre GSM Market & Complex",
    "Kwankwasiyya City Plaza",

    // Leisure & Lifestyle Hubs
    "Kano Zoological Garden",
    "Gidan Rumfa Palace Grounds",
    "Kofar Mata Dye Pits",
    "Kano Polo Club",
    "Tiga Dam & Resort",
    "Challawa Gorge Dam Picnic Spot",
    "Kano Race Course",
    "Kofar Nassarawa",

    // Central & General Commodity Markets
    "Kantin Kwari Textile Market",
    "Sabon Gari Market",
    "Dawanau International Grains Market",
    "Kurmi Market",
    "Singer Market",
    "Kofar Wambai Market",
    "Kwankwasiyya Market",
    "Bompai Market",

    // Specialized Commodity Hubs
    "Yan Lemo Fruit Market",
    "Yankura Spare Parts Market",
    "Sharada Industrial Market",
    "Kofar Mazugal Market",
    "Kasuwan Wanki (Dye Market)",
    "Kasuwan Kurmi Leather Section",
    "Kofar Ruwa Building Materials Market",
    "Farm Centre GSM & Electronics Market",
    "Hadejia Road Auto Parts Market",

    // Emerging & Satellite Hubs
    "Kumbotso Market",
    "Gwarzo Road Market",
    "Hotoro Market",
    "Rimi Market",

    // Central Administrative Areas
    "Kano Municipal",
    "Kofar Nassarawa",
    "Kofar Mata",
    "Kofar Dan Agundi",
    "Kofar Kabuga",

    // Institutional / Academic Areas
    "Gwale",
    "Dorayi",
    "Kofar Famfo",
    "Hotoro",
    "Unguwa Uku",
    "Rimin Gata",
    "Bompai",
    "Sharada",
    "Yankaba",
    "Dakata",

    // High-Density Institutional Corridors
    "Zaria Road",
    "BUK Road",
    "Airport Road",
    "Gyadi-Gyadi",
    "Naibawa",
    "Tarauni",

    // Leisure & Lifestyle Corridors
    "Sabon Gari",
    "Fagge",
    "Nassarawa GRA",
    "Bompai",
    "Tarauni",
    "Zaria Road Recreation",
    "Club Road / Race Course Road",
    "Airport Road Leisure Belt",

    // Shopping & Entertainment Hubs
    "Kano City Centre",
    "Ado Bayero Mall",
    "Farm Centre",
    "Kofar Ruwa",
    "Sharada Market",
    "Kwankwasiyya City Layout",

    // Public Leisure & Outdoor Spaces
    "Kofar Mata Recreational Axis",
    "Gidan Rumfa Area (Emir’s Palace Vicinity)",
    "Race Course Road Grounds",
    "Zoological Garden",
    "Bompai Recreational",
  ],
  Kaduna: [
    "Barnawa",
    "Kaduna North",
    "Ungwan Rimi",
    "Sabo",
    "Television",
    "Kawo",
    "Central Market",
  ],
  Jos: [
    "Terminus Market",
    "Rayfield",
    "Angwan Rukuba",
    "Bukuru",
    "Gyero",
    "Zarmaganda",
  ],
  Maiduguri: ["Baga Road Market", "Gomari", "Mairi", "Custom", "Bulunkutu"],
  Ilorin: ["Tanke", "Oja Oba", "Surulere", "Taiwo", "Geri Alimi"],
  Akure: ["Oba Adesida Road", "Oke Ijebu", "FUTA South Gate", "Araromi"],
  Ibadan: [
    "Bodija",
    "Dugbe",
    "Challenge",
    "Mokola",
    "Sango",
    "Apata",
    "Orita Mefa",
  ],
  Calabar: [
    "Marian Road",
    "Eight Miles",
    "Watt Market",
    "Ikot Ansa",
    "Goldie",
    "Akim",
  ],
  Warri: ["Effurun", "Ekpan", "Udu Road", "Airport Road", "Jakpa", "Okere"],
  Abeokuta: ["Panseke", "Kuto", "Oke Ilewo", "Ijaye", "Adigbe", "Lafenwa"],
  Makurdi: ["Wadata", "High Level", "Modern Market", "North Bank"],
};
